-- THIS MIGRATION HAS BEEN SUPERSEDED.
-- It used a timestamp (20240101) that sorts BEFORE the init migration (202502...),
-- causing it to attempt ALTER TABLE "User" before "User" is created.
--
-- The corrected migration is at:
--   prisma/migrations/20250601000000_add_admin_roles/migration.sql
--
-- Please delete this folder from your migration history.
-- You can do so with:
--   rm -rf prisma/migrations/20240101000000_add_admin_roles
